macro(add_photk_executable name)
  add_executable(${name} ${ARGN})
  foreach(lib ${PHOTK_USED_LIBS})
    target_link_libraries( ${name} ${lib} )
  endforeach(lib)
endmacro(add_photk_executable name)

macro(add_photk_tool name)
  add_photk_executable(${name} ${ARGN})
  if( PHOTK_BUILD_TOOLS )
    message( "Installing: " ${name} )
    install(TARGETS ${name} RUNTIME DESTINATION bin)
  endif()
  set_target_properties(${name} PROPERTIES FOLDER "tools")
endmacro(add_photk_tool name)

function(photk_enable_testing)
  enable_testing()
  set(GTEST_ROOT ${PHOTK_SOURCE_DIR}/thirdparty/gtest)
  message( "GTEST ROOT: " ${GTEST_ROOT} )
  find_package(GTest REQUIRED)
endfunction(photk_enable_testing)
